name: build
on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Setup Nuget
      uses: Nuget/setup-nuget@v1.0.5

    - name: Restore nuget packages
      run: nuget restore Advocate.sln

    - name: Build
      run: msbuild Advocate.sln /p:Configuration=Release

    - name: Extract Short Commit Hash
      id: extract
      shell: bash
      run: echo ::set-output name=commit::`git rev-parse --short HEAD`
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: RePak-${{ steps.extract.outputs.commit }}
        path: |
          x64/${{ env.BUILD_PROFILE }}/*.dll
          x64/${{ env.BUILD_PROFILE }}/*.exe
          x64/${{ env.BUILD_PROFILE }}/*.pdb
          x64/${{ env.BUILD_PROFILE }}/*.txt
