name: build
on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup Nuget
      uses: Nuget/setup-nuget@v1.0.7

    - name: Restore nuget packages
      run: nuget restore Advocate.sln

    - name: Build
      run: msbuild Advocate.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=x64
      
    - name: Extract Short Commit Hash
      id: extract
      shell: bash
      run: echo ::set-output name=commit::`git rev-parse --short HEAD`
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Advocate-${{ steps.extract.outputs.commit }}
        path: |
          bin/Publish/x64/*.dll
          bin/Publish/x64/*.exe
          bin/Publish/x64/*.pdb
          bin/Publish/x64/*.txt
