name: format-check

on: pull_request

jobs:
  check-format:
    runs-on: windows-latest

    # this is a comment
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install dotnet-format tool
        run: dotnet tool install -g dotnet-format
        
      - name: Run dotnet format
        run:
          dotnet format
      
      # this is awful but without --verify-no-changes it always returns exit code 0
      # and with --verify-no-changes it logs them in a shit way
      - name: Return status
        run:
          dotnet format --verify-no-changes -v q
      