name: format-check

on:
  push:
    paths:
      - "**.cs"
      - ".editorconfig"
  pull_request:
    paths:
      - "**.cs"
      - ".editorconfig"

jobs:
  check-format:
    runs-on: windows-latest

    steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

  