name: format-check

on: [push, pull_request]

jobs:
  check-format:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format --version 3.3.111304
        
      - name: Run dotnet format
        id: format
        uses: xt0rted/dotnet-format@v1.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          action: "fix"
          only-changed-files: true
          folder: "."

      - name: Get diffs
        shell: bash
        run: |
          git diff "$GITHUB_SHA" > format-diff
          cat format-diff
  
      - name: Return result from dotnet-format
        if: steps.format.outputs.has-changes == 'true'
        run: exit 1