name: format-check

on: [push, pull_request]

jobs:
  check-format:
    runs-on: windows-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format --version 3.3.111304
        
      - name: Run dotnet format
        id: format
        uses: xt0rted/dotnet-format@v1.2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          action: "fix"
          only-changed-files: true
          folder: "."

      - name: Get diffs
        shell: bash
        id: diff
        run: |
          git diff "$GITHUB_SHA" > format-diff
          echo ::set-output name=format-diff::$(cat format-diff)

      - name: Test output
        run: echo ${{ steps.vars.outputs.format-diff }}
  
      - name: Result
        if: steps.format.outputs.has-changes == 'true'
        run: |
          cat format-diff
          exit 1